### ISSUE TITLE
Using Hyperref causes corruption of references

### ISSUE THREAD

**Issue by bryce-carson** [JoeRiel/knoweb#2]
When I compile my document with $Lua\LaTeX$ I can get a proper document, with alpha subpage chunk numbering working correctly. This is the only engine with which I'm able to compile the document and get it working at an acceptable level.

If I use the hyperref package, however, it corrupts the document (regardless of whether I load it before or after knoweb): [test.pdf](https://github.com/JoeRiel/knoweb/files/12386373/test.pdf)

Without the hyperref package the document looks like this: [test.pdf](https://github.com/JoeRiel/knoweb/files/12386380/test.pdf)

The Makefile I wrote and the test file are given below.
```make
weave: clean
	noweave -delay -autodefs cee -index test.nw > test.tex

compile-pdf: tangle weave
	latexmk --lualatex --interaction=nonstopmode -f test.tex
	lualatex test.tex

tangle: clean
	notangle -Rtest.c test.nw > test.c

# Remove backup files and LaTeX garbage and cache files.
clean:
	$(RM) *~ *.pdf *.dvi *.log *.blg *.toc *.out *.brf *.lof *.idx *.xdy *.tex *.aux *.fdb_latexmk *.fls
	$(RM) test.c
```

```noweb
%% -*- mode: Poly-Noweb; noweb-code-mode: emacs-lisp-mode; fill-column: 72; eval: (emacsql-fix-vector-indentation) -*-
% Copyright © 2023 Bryce Carson
\documentclass[12pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage{mparhack}
\usepackage{mathptmx}

\usepackage[footnotesizecode,longchunks]{knoweb}

\usepackage{xspace}
\usepackage{syntax}
\usepackage{paralist}
\usepackage{color}

\pagestyle{noweb}

\begin{document}

The document should compile fine, and the references should all simply
work. This is an MWE.

<<A>>=
;; This is test.el, an Emacs Lisp file to test knoweb reproducibly.
int add_one(int a);
<<B>>
<<B>>=
int add_one(int a) {
  return a + 1;
}

<<C>>
@
\newpage
<<C>>=
main() {
  printf("%d\n", add_one(1));
}
@ 

Finally, [[A]], [[B]], and [[C]] will be collated in [[test.c]].
<<test.c>>=
<<A>>
@ 

\section{Appendices}
\subsection{A: Chunks}
\nowebchunks

\subsection{B: Identifiers}
\nowebindex

\end{document}
```

**Comment by bryce-carson** [comment]
```
[bryce@fedora ~]$ dnf info texlive-scheme-full
Last metadata expiration check: 0:00:38 ago on Sat 19 Aug 2023 11:28:23 AM MDT.
Installed Packages
Name         : texlive-scheme-full
Epoch        : 10
Version      : svn54074
Release      : 65.fc38
Architecture : noarch
Size         : 0.0  
Source       : texlive-2022-65.fc38.src.rpm
Repository   : @System
From repo    : fedora
Summary      : full scheme (everything)
URL          : http://tug.org/texlive/
License      : Apache-2.0 AND Artistic-2.0 AND CC0-1.0 AND CC-BY-3.0 AND
             : CC-BY-4.0 AND CC-BY-SA-3.0 AND CC-BY-SA-4.0 AND GPL-2.0-only AND
             : GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-2.1-or-later AND
             : LPPL-1.2 AND LPPL-1.3c AND MIT AND
             : LicenseRef-Fedora-Public-Domain AND LicenseRef-Utopia
Description  : This is the full TeX Live scheme: it installs everything
             : available.
```

**Comment by bryce-carson** [comment]
```
Last metadata expiration check: 1:33:13 ago on Sat 19 Aug 2023 09:57:14 AM MDT.
Package texlive-hyperref-10:svn65014-65.fc38.noarch is already installed.
```

**Comment by JoeRiel** [comment]
Hi Bryce,
I didn't have latexmk installed, but just did so.  I don't have cee, so changed the weave target in your Makefile to noweave -delay -index test.nw > test.tex.  I added a usepackage for hyperref to the nw file:
`\usepackage[footnotesizecode,longchunks]{knoweb}
\usepackage[colorlinks,backref]{hyperref}
`
The compile-pdf then produces what appears to be the document you are looking for.

**Comment by bryce-carson** [comment]
`cee` is the auto-definitions file for the C language provided with Noweb; the file is called `autodefs.cee`. You /should/ have it; check with `noweave -showautodefs` to be sure.

**Comment by bryce-carson** [comment]
[test.pdf](https://github.com/JoeRiel/knoweb/files/12388800/test.pdf)
When I make those same changes, and optionally include the noweb option `alphasubpage`, the document does not compile with alpha-subpage references. The colorlinks work, but all chunks on the same page are given the same margintag chunk number (1 for page one chunks, two for page two chunks; see the document).

With `-autodefs cee` included, with hyperref loaded the way you suggest, the document appear as so: 
[test.pdf](https://github.com/JoeRiel/knoweb/files/12388802/test.pdf)

**Comment by bryce-carson** [comment]
[test.log](https://github.com/JoeRiel/knoweb/files/12388803/test.log)

**Comment by JoeRiel** [comment]
While I don't have autodefs.cee (nor is it in Debian), I do have autodefs.c, so went with that in the call to noweave: noweave -delay -autodefs c -index test.nw > test.tex.  The resulting pdf looks like the previous; the Defines section at the end of page 1 is "add_one used in chunks 1a and 2a," with 1a and 2a being hyperlinks to the chunk definitions.

**Comment by bryce-carson** [comment]
> While I don't have autodefs.cee (nor is it in Debian), I do have autodefs.c, so went with that in the call to noweave: noweave -delay -autodefs c -index test.nw > test.tex.  The resulting pdf looks like the previous; the Defines section at the end of page 1 is "add_one used in chunks 1a and 2a," with 1a and 2a being hyperlinks to the chunk definitions.

Interesting. I see 1 and 2<2 in 0.

Can you share the tex file, log, and what $\LaTeX$ compiler and package versions you're using, including what Noweb and Awk?

**Comment by JoeRiel** [comment]
How do I get the files into GitHub?  This comment box has text that says "Attach files by dragging & dropping, selecting or pasting them." Should be easy, but I have no idea how to drag/drop/select a file on my machine; shouldn't there be a button to click that queries for the file name?

**Comment by bryce-carson** [comment]
Yes, you may also click that area of the screen and it acts like an
"upload" button, opening a file chooser.

**Comment by JoeRiel** [comment]
I'm an idiot.  What area of the screen?  How do I "click" it?  Right clicking in this comment dialog just brings up a useless menu with options Undo, Paste, etc.  Nothing that indicates it will query for a filepath.

**Comment by bryce-carson** [comment]
If you left-click that same text you mentioned it will open a dialoge to select files.

**Comment by JoeRiel** [comment]
Thanks.  
[test.log](https://github.com/JoeRiel/knoweb/files/12388900/test.log)
[test.pdf](https://github.com/JoeRiel/knoweb/files/12388901/test.pdf)

**Comment by JoeRiel** [comment]
My latex version appears (from latex -v) to be
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020/Debian)
The awk -V returns GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)
noweb appears to be 2.12.

**Comment by JoeRiel** [comment]
latexmk -v shows Latexmk, John Collins, 29 September 2020. Version 4.70b.

**Comment by bryce-carson** [comment]
Can you also upload `test.tex` so I can check if Noweave or a filter is the culprit (I'm going to `diff` them)? I'm unsure the differences in our versions of gawk, latekmk, lualatex, and pdftex are causing the issue I'm seeing.

**Comment by JoeRiel** [comment]
[test.tex.gz](https://github.com/JoeRiel/knoweb/files/12389001/test.tex.gz)
Had to gzip to allow this site to get it.

**Comment by bryce-carson** [comment]
I don't see any important differences between the $\LaTeX$ files, so the culprit is the $\LaTeX$ _compilers_ we are using. I tried using TeXLive in Debian 12, but that still suffered from "missing number" errors. I'm about to test a Debian 11 virtual machine, which will let me use the same TeXLive installation as you (I hope that resolves the issue).

If that works well, then I can approach Stack Exchange with some useful information to debug the issue.

**Comment by JoeRiel** [comment]
I was getting similar errors when \usepackage{hyperref} was placed before \usepackage{knoweb}; swapping them eliminated the errors.

**Comment by bryce-carson** [comment]
I'm happy to report that it doesn't appear to be an issue with the knoweb style at all, because when I compile the document under Debian 11 with TeXLive 2020 (the version available on Debian 11) it compiles _without any_ errors, warnings, etc (perfect!)

I'm going to close this issue, since the culprit of the document corruption is due to TeXLive.

**Comment by bryce-carson** [comment]
I'm happy to report that it doesn't appear to be an issue with the knoweb style at all, because when I compile the document under Debian 11 with TeXLive 2020 (the version available on Debian 11) it compiles _without any_ errors, warnings, etc (perfect!)

I'm going to close this issue, since the culprit of the document corruption is due to TeXLive.

**Comment by bryce-carson** [comment]
> I was getting similar errors when \usepackage{hyperref} was placed before \usepackage{knoweb}; swapping them eliminated the errors.

That's interesting! I guess I was lucky I placed it after knoweb, following your instruction. It was still required to use the 2020 version of TeXLive.
